# Generated by Django 2.2.3 on 2019-07-17 00:05

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGistExtension(),
    ]
