# Generated by Django 2.2.3 on 2019-08-29 03:55

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import voucher.contrib.postgres.constraints


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('during', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=voucher.contrib.postgres.constraints.ExclusionConstraint(expressions=[('during', '&&'), ('code', '=')], name='exclude_overlapping_vouchers'),
        ),
    ]
