# Generated by Django 2.2.4 on 2019-08-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20190829_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default='SNSD', max_length=10),
        ),
    ]
